/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-05-14 15:59:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import twitter.Tweet;
import java.util.List;

public final class conversacion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("twitter.Tweet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Conversacion</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
 String usuario = (String) request.getAttribute("usuario"); 	
      out.write('\n');
      out.write('	');
 if(usuario != null ) { 	
      out.write("\n");
      out.write("\t\t<p>\n");
      out.write("\t\t\t<form action=\"logout\">\n");
      out.write("\t\t        <input type=\"submit\" value=\"Cerrar Sesión\">\n");
      out.write("\t\t    </form>\n");
      out.write("\t\t\t<form action=\"timeline\">\n");
      out.write("\t\t        <input type=\"submit\" value=\"Ir a Vista Principal\">\n");
      out.write("\t\t    </form>\n");
      out.write("\n");
      out.write("\t\t</p>\n");
      out.write("\t");
 } 
      out.write('\n');
      out.write('\n');
      out.write('\n');
 Tweet original = (Tweet) request.getAttribute("original"); 	
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div>\t\t\t\t\n");
      out.write("                <a href=\"profile?profile=");
      out.print(original.getAutor_name() );
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( original.getAutor_name() );
      out.write(" </a>\n");
      out.write("\t\t\t\t<a href=\"conversacion?id_msg=");
      out.print(original.getId() );
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( original.getMensaje() );
      out.write("</a>\n");
      out.write("\t\t\t\t<label> ");
      out.print( original.datetime() );
      out.write("</label>\n");
 if(usuario != null ) { 	
      out.write("\n");
      out.write("                <form action=\"retransmision\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"mensaje\" value=\"");
      out.print( original.getId() );
      out.write("\">\n");
      out.write("\t\t\t\t    <input type=\"submit\" value=\"RTx\">\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<form action=\"publish\" method=\"post\">\n");
      out.write("\t\t        <div>\n");
      out.write("\t\t\t\t\t<p><textarea name=\"mensaje\" rows=\"3\" cols=\"80\" placeholder=\"Responde a este mensaje\"></textarea></p>\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"responde_a\" value=\"");
      out.print( original.getId() );
      out.write("\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t        <input type=\"submit\" value=\"Publicar tu respuesta\">\n");
      out.write("\t\t    </form>\n");
      out.write("\t\t</div>\n");
      out.write(" ");
 } 
      out.write('\n');
      out.write('\n');
 List<Tweet> answers = (List<Tweet>) request.getAttribute("answers"); 
      out.write('\n');
 for (Tweet tweet: answers) { 
      out.write("\n");
      out.write("        <div>\t\t\t\t\n");
      out.write("                <a href=\"profile?profile=");
      out.print(tweet.getAutor_name() );
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( tweet.getAutor_name() );
      out.write(" </a>\n");
      out.write("\t\t\t\t<a href=\"conversacion?id_msg=");
      out.print(tweet.getId() );
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( tweet.getMensaje() );
      out.write("</a>\n");
      out.write("\t\t\t\t<label> ");
      out.print( tweet.datetime() );
      out.write("</label>\n");
 if(usuario != null ) { 	
      out.write("\n");
      out.write("                <form action=\"retransmision\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"mensaje\" value=\"");
      out.print( tweet.getId() );
      out.write("\">\n");
      out.write("\t\t\t\t    <input type=\"submit\" value=\"RTx\">\n");
      out.write("\t\t\t\t</form>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("        </div>\n");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
